-- Gloss — initial schema.
--
-- The CreateTable / CreateIndex / AddForeignKey blocks below are generated by
-- `prisma migrate diff` from prisma/schema.prisma. Everything after the
-- "BEYOND PRISMA" banner is hand-written: RLS, the lower(term) index, the
-- auth.users foreign keys, the hit counter, and the private storage bucket
-- cannot be expressed in the Prisma schema language. If you change a table,
-- regenerate the top half; keep the bottom half.

-- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "books" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "source_lang" TEXT,
    "storage_path" TEXT NOT NULL,
    "pages" JSONB NOT NULL,
    "page_count" INTEGER NOT NULL,
    "last_page" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "books_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "words" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "book_id" UUID,
    "term" TEXT NOT NULL,
    "lemma" TEXT,
    "translation" TEXT NOT NULL,
    "context" TEXT,
    "page" INTEGER,
    "kind" TEXT NOT NULL DEFAULT 'word',
    "ease" REAL NOT NULL DEFAULT 2.5,
    "interval" INTEGER NOT NULL DEFAULT 0,
    "reps" INTEGER NOT NULL DEFAULT 0,
    "due_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "words_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "translations" (
    "hash" TEXT NOT NULL,
    "source_lang" TEXT,
    "target_lang" TEXT,
    "source_text" TEXT NOT NULL,
    "translation" TEXT NOT NULL,
    "hits" INTEGER DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "translations_pkey" PRIMARY KEY ("hash")
);

-- CreateIndex
CREATE INDEX "books_user" ON "books"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "words_due" ON "words"("user_id", "due_at");

-- AddForeignKey
ALTER TABLE "words" ADD CONSTRAINT "words_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ════════════════════════════════════════════════════════════════════
-- BEYOND PRISMA — not expressible in schema.prisma
-- ════════════════════════════════════════════════════════════════════

-- ── ownership ───────────────────────────────────────────────────────
-- Prisma must not manage the `auth` schema, so these FKs are added here.
ALTER TABLE "books" ADD CONSTRAINT "books_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "words" ADD CONSTRAINT "words_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;

-- ── constraints Prisma cannot express ───────────────────────────────
-- The same term may be kept once per book. lower() makes it case-insensitive,
-- and Prisma has no syntax for a function call inside an index.
CREATE UNIQUE INDEX "words_unique" ON "words" ("user_id", lower("term"), "book_id");

ALTER TABLE "words" ADD CONSTRAINT "words_kind_check"
  CHECK ("kind" IN ('word', 'phrase'));

-- ── row level security ──────────────────────────────────────────────
-- This is what keeps a book you upload yours. Prisma connects as the database
-- owner and bypasses all of it; the app never connects that way.
ALTER TABLE "books" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "words" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "translations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY books_own ON "books"
  FOR ALL TO authenticated
  USING ("user_id" = auth.uid())
  WITH CHECK ("user_id" = auth.uid());

CREATE POLICY words_own ON "words"
  FOR ALL TO authenticated
  USING ("user_id" = auth.uid())
  WITH CHECK ("user_id" = auth.uid());

-- Shared cache: no user data in it. Readable by any signed-in user; only the
-- Edge Function writes, and it uses the service role key (which bypasses RLS),
-- so no insert/update policy is granted here.
CREATE POLICY translations_read ON "translations"
  FOR SELECT TO authenticated
  USING (true);

-- ── counting cache hits without a read-then-write race ──────────────
CREATE OR REPLACE FUNCTION bump_translation_hits(h text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE translations SET hits = hits + 1 WHERE hash = h;
$$;

-- ── storage: the private books bucket ───────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('books', 'books', false)
ON CONFLICT (id) DO NOTHING;

-- Files live at {user_id}/{book_id}/{filename}, so the first path segment is
-- the owner.
CREATE POLICY books_bucket_own ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'books'
    AND (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'books'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
